# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainPlayersTable extends _ModuleTable

var player_id: MainPlayersPlayerIdUniqueIndex

func _init(p_local_db: LocalDatabase) -> void:
	super(p_local_db)
	set_meta("table_name", "players")
	player_id = MainPlayersPlayerIdUniqueIndex.new(p_local_db)

func iter() -> Array[MainPlayers]:
	var rows: Array = super()
	var typed_array: Array[MainPlayers] = []
	typed_array.assign(rows)
	return typed_array
