# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainHeartbeatPlayer extends Resource

const module_name : String = "Main"
const table_names: Array[String] = []

@export var player_id: String
@export var last_seen_unix_ms: float

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('bsatn_type_player_id', &'string')
	set_meta('bsatn_type_last_seen_unix_ms', &'f64')

## 0. player_id: String[br]
## 1. last_seen_unix_ms: float[br]
static func create(p_player_id: String, p_last_seen_unix_ms: float) -> MainHeartbeatPlayer:
	var result: MainHeartbeatPlayer = MainHeartbeatPlayer.new()
	result.player_id = p_player_id
	result.last_seen_unix_ms = p_last_seen_unix_ms
	return result
