# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
@tool
class_name MainUpsertPlayer extends Resource

const module_name : String = "Main"
const table_names: Array[String] = []

@export var player_id: String
@export var browser_fingerprint: String
@export var display_name: String
@export var guild: String
@export var role: String
@export var player_state: String
@export var pos_x: float
@export var pos_y: float
@export var last_seen_unix_ms: float

func _init() -> void:
	_reset_metadata()

func _reset_metadata() -> void:
	# Clear old metadata
	for key : StringName in get_meta_list():
		set_meta(key, null)

	set_meta('bsatn_type_player_id', &'string')
	set_meta('bsatn_type_browser_fingerprint', &'string')
	set_meta('bsatn_type_display_name', &'string')
	set_meta('bsatn_type_guild', &'string')
	set_meta('bsatn_type_role', &'string')
	set_meta('bsatn_type_player_state', &'string')
	set_meta('bsatn_type_pos_x', &'f64')
	set_meta('bsatn_type_pos_y', &'f64')
	set_meta('bsatn_type_last_seen_unix_ms', &'f64')

## 0. player_id: String[br]
## 1. browser_fingerprint: String[br]
## 2. display_name: String[br]
## 3. guild: String[br]
## 4. role: String[br]
## 5. player_state: String[br]
## 6. pos_x: float[br]
## 7. pos_y: float[br]
## 8. last_seen_unix_ms: float[br]
static func create(p_player_id: String, p_browser_fingerprint: String, p_display_name: String, p_guild: String, p_role: String, p_player_state: String, p_pos_x: float, p_pos_y: float, p_last_seen_unix_ms: float) -> MainUpsertPlayer:
	var result: MainUpsertPlayer = MainUpsertPlayer.new()
	result.player_id = p_player_id
	result.browser_fingerprint = p_browser_fingerprint
	result.display_name = p_display_name
	result.guild = p_guild
	result.role = p_role
	result.player_state = p_player_state
	result.pos_x = p_pos_x
	result.pos_y = p_pos_y
	result.last_seen_unix_ms = p_last_seen_unix_ms
	return result
