# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

const Players = preload('res://spacetime_bindings/schema/types/main_players.gd')
const HeartbeatPlayer = preload('res://spacetime_bindings/schema/types/main_heartbeat_player.gd')
const UpsertPlayer = preload('res://spacetime_bindings/schema/types/main_upsert_player.gd')
