# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainModuleDb extends RefCounted

const table_names : Array[String] = ["players"]

var players: MainPlayersTable

func _init(p_local_db: LocalDatabase) -> void:
	players = preload('res://spacetime_bindings/schema/tables/main_players_table.gd').new(p_local_db)
