# THIS FILE IS AUTOMATICALLY GENERATED BY THE SPACETIMEDB ADDON. EDITS TO THIS
# FILE WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.
class_name MainModuleReducers extends RefCounted

var _client: SpacetimeDBClient

func _init(p_client: SpacetimeDBClient) -> void:
	_client = p_client
## 0. player_id: String [br]
## 1. last_seen_unix_ms: float [br]
func heartbeat_player(player_id: String, last_seen_unix_ms: float, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('heartbeat_player', [player_id, last_seen_unix_ms], [&'string', &'f64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

## 0. player_id: String [br]
## 1. browser_fingerprint: String [br]
## 2. display_name: String [br]
## 3. guild: String [br]
## 4. role: String [br]
## 5. player_state: String [br]
## 6. pos_x: float [br]
## 7. pos_y: float [br]
## 8. last_seen_unix_ms: float [br]
func upsert_player(player_id: String, browser_fingerprint: String, display_name: String, guild: String, role: String, player_state: String, pos_x: float, pos_y: float, last_seen_unix_ms: float, cb: Callable = func(_t: TransactionUpdateMessage) -> void: pass) -> Error:
	var __handle__ : SpacetimeDBReducerCall = _client.call_reducer('upsert_player', [player_id, browser_fingerprint, display_name, guild, role, player_state, pos_x, pos_y, last_seen_unix_ms], [&'string', &'string', &'string', &'string', &'string', &'string', &'f64', &'f64', &'f64'])
	if __handle__.error: return __handle__.error
	var __result__: TransactionUpdateMessage = await __handle__.wait_for_response()
	if cb.is_valid():
		cb.call(__result__)
	else:
		return ERR_METHOD_NOT_FOUND
	return OK

